### ISSUE TITLE
Optimizing VQE workflow for a IBM quantum system

### ISSUE THREAD

**Issue by HwajungKang** [qiskit-advocate/qamp-spring-22#15]
### Description

The goal of this project is for you to gain the knowledge of the full workflow of running VQE on a IBM Quantum system. 

You will learn the VQE basics and several techniques that can be implemented to improve the fidelity of the outcomes when running the circuits on a near-term quantum computer by building your own VQE example to execute on an IBM Quantum system.  

You will understand the purpose of the variational algorithm for a near-term quantum computer, how to construct a parametrized circuit to measure energy expectation value for a given Hamiltonian, apply Mapomatic (https://github.com/Qiskit-Partners/mapomatic) to find a good compiled circuit with the lowest noise, understand the need for a particular optimization algorithm like SPSA when running on a real quantum computer. We will also utilize measurement mitigation techniques in several versions, full, tensored and finally M3 (https://journals.aps.org/prxquantum/abstract/10.1103/PRXQuantum.2.040326), (https://github.ibm.com/IBM-Q-Software/mthree) and understand the reasons for these different approaches. 

### Deliverables

A jupyter notebook that can be a tutorial

### Mentors details

- Mentor 1
  - Name: Hwajung Kang
  - GitHub ID: HwajungKang
  - What they do: Education Delivery Program Manager

### Number of mentees

1

### Type of mentees

  - Required:
    - Basics of quantum computing and Qiskit
    - Python basics
    - Github experience
  - Nice to have:
    - Experience of using IBM Quantum systems

**Comment by HuangJunye** [comment]
Closing this issue as it was not paired with any mentee. Thank you for suggesting the project idea!
