### ISSUE TITLE
quirk - qiskit integration

### ISSUE THREAD

**Issue by 1ucian0** [qiskit-advocate/qamp-spring-22#19]
### Description

[Quirk](https://algassert.com/quirk) is a famous circuit composer and simulator, written by [Craig Gidney](https://github.com/Strilanc). It is super flexible and it wold be great to have some sort of integration with Qiskit. Here are some ideas:
 * Export a Qiskit QuantumCircuit as a [Quirk url](https://github.com/Strilanc/Quirk/wiki/How-to-use-Quirk#url-circuit-editing)
 * Import a Quirk json as a Qiskit QuantumCircuit
 * Have Quirk as a QuantumCircuit builder, like an alternative to [the composer widget](https://quantum-computing.ibm.com/lab/docs/iql/composer-widget) 

### Deliverables

a python package (called `qiskit-quirk`?) with some of the integrations. 

### Mentors details

- Mentor 1
  - Name: Amir Ebrahimi
  - GitHub ID: @amirebrahimi
  - What they do:

### Number of mentees

1

### Type of mentees

- Mentee 1
  - Required:
    - Interested in web and front-end
    - Some knowledge of circuit construction in Qiskit
  - Nice to have:
    - Experience with jupyter widgets
    - Knowledge in nodejs (for creating a standalone version, for example)

**Comment by 1ucian0** [comment]
Hi @diemilio , pyQuirk looks great! I was not aware of it. It makes total sense to use QASM2 as shared format. Indeed, it look exactly like the thing I was looking for. I will have a deeper look in the coming days.

@HuangJunye shall I close this issue?

**Comment by amirebrahimi** [comment]
Hi @HuangJunye. Sure I'd be happy to mentor.

**Comment by HuangJunye** [comment]
@amirebrahimi That's great. Thank you for signing up as mentor. I will contact you on Slack for details.

**Comment by HuangJunye** [comment]
Closing this issue as it was not paired with any mentee. Thank you for suggesting the project idea!
