### ISSUE TITLE
Create tools for the protein folding problem in Qiskit Nature

### ISSUE THREAD

**Issue by dlasecki** [qiskit-advocate/qamp-spring-22#24]
### Description

Protein folding is the newest sampling problem released in Qiskit nature 0.2.0 (https://github.com/Qiskit/qiskit-nature/tree/main/qiskit_nature/problems/sampling/protein_folding). We would like to implement some convenience tools and extend the implementation to allow for better result interpretation and visualization of the final output.

Related issues from qiskit-nature:
https://github.com/Qiskit/qiskit-nature/issues/313
https://github.com/Qiskit/qiskit-nature/issues/235
https://github.com/Qiskit/qiskit-nature/issues/236

### Deliverables

Implementation for Qiskit nature. A PR related to this would be a tangible deliverable.

### Mentors details

- Mentor 1
  - Name: Panagiotis Barkoutsos
  - GitHub ID: @pbark
  - What they do: Qiskit Nature core developer / researcher
- Mentor 2
  - Name: Dariusz Lasecki
  - GitHub ID:@dlasecki
  - What they do: Qiskit Applications software engineer

### Number of mentees

1

### Type of mentees

- Mentee 1
  - Required:
    - Good knowledge of Python.
  - Nice to have:
    - Familiarity with Qiskit Nature.
    - Familiarity with protein folding problem.
    - Experience with Matplotlib.

**Comment by HuangJunye** [comment]
Closing this issue as it was not paired with any mentee. Thank you for suggesting the project idea!
