### ISSUE TITLE
Connect an open-source FEM solver and renderer backend to Qiskit Metal

### ISSUE THREAD

**Issue by AbeerVaishnav13** [qiskit-advocate/qamp-spring-22#28]
### Description

The [Qiskit Metal](https://qiskit.org/metal) project aims towards developing an open-source end-to-end toolchain for Superconducting quantum device design. This requires an in-built GUI to render the components of the chip as well as a connection to a FEM solver to obtain parasitic capacitance matrix and/or electromagnetic fields associated with the on-chip components, and. then use them to tune the component parameters for best real-world performance.

Presently Qiskit Metal only connects to the Ansys Q3D and HFSS backends, which are not open-source and thus, cannot be accessed by everyone.

The goal of this project is to pick an open-source FEM solver (like [FreeFEM](https://freefem.org/), [Elmer](http://www.elmerfem.org/blog/), etc) or generic PDE solvers (like [FEniCS Project](https://fenicsproject.org/)), and develop a connection interface to Qiskit Metal to make superconducting device design more accessible with a fully open-source design pipeline!

### Deliverables

- Python script for the Qiskit Metal to FEM software renderer
- A jupyter notebook for reference implementation and demo
- A possible PR to the [Qiskit Metal GitHub repo](https://github.com/Qiskit/qiskit-metal) (can continue to work on this and refine it even after QAMP-Spring-22!)

### Mentors details

- Mentor 1
  - Name: TBD
  - GitHub ID: TBD
  - What they do: TBD

### Number of mentees

2

### Type of mentees

- Mentee 1
  - Required:
    - Good knowledge of Python
    - Basic knowledge of electronic circuit analysis and Electromagnetic theory
  - Nice to have:
    - Some experience with using GUI (or CLI) based FEM solver softwares.
    - Basic knowledge of superconducting qubits and cQED (some useful resources: [1](https://www.youtube.com/watch?v=eZJjQGu85Ps&list=PLOFEBzvs-VvrXTMy5Y2IqmSaUjfnhvBHR&index=17), [2](https://www.youtube.com/watch?v=Nksr4_prTfw&list=PL1CFLtxeIrQqihzJvb8WdX-3dh8cx-mZv), [3](https://www.youtube.com/watch?v=bigXRd042Co&list=PL1CFLtxeIrQrtx6WmMG_pwk-Y7AGTv1_O))
    - Knowledge of different analyses in Qiskit Metal (Lumped Capacitive, Quasi-Lumped, EPR)

**Comment by PAPACOTAS** [comment]
Would be great to have this!

**Comment by diemilio** [comment]
This would be a great addition to `qiskit-metal`. I would love to apply to this project but I am a bit worried that, since I do not have access to ANSYS, it would be extremely difficult to debug the functionality/connectivity of the new FEM tool. What do you think @AbeerVaishnav13?

**Comment by AbeerVaishnav13** [comment]
Hi all, it turns out that this project is a bit too long and time consuming to be completed successfully within the time limit of QAMP Spring22. Instead, we are planning to take on this project separately as an independent project/contribution for Qiskit Metal. If you're interested to join in, please comment here or DM me on Qiskit slack. Thanks!
