### ISSUE TITLE
Integration of Qiskit with Web3.0

### ISSUE THREAD

**Issue by robertloredo** [qiskit-advocate/qamp-spring-22#29]
### Description

[Web3](https://en.wikipedia.org/wiki/Web3) is a term used to describe the decentralized and token-based economics, provided by blockchain technology. Since its emergence many years ago via popular coins and platforms, Bitcoin, Ethereum, etc. lots of development has grown out of this technology. Nowadays more and more commercial applications and companies are getting into Web3.

For this project we would like to see if there are any potential areas where we can see how to integrate Qiskit, and quantum computing in general, to the Web3 area, asides from the already popular cryptography topic, which everyone is already writing and reading about. :) 

Here's a short list of topics to consider as an example: 
- How could adding quantum image processing add value to artifacts such as NFTs, token-economics, etc.?
- Are there any L1/L2 components or artifacts that can benefit by quantum? 
- Some decentralization applications rely on various heavy computational tasks, can we find any that have quantum potential? 

### Deliverables

As a deliverable ideally we would like to complete the following: 

- [ ] Research potential areas where quantum might provide computational value
- [ ] List out specifics around the computational advantage
- [ ] Complete a simple example using Qiskit
- [ ] Write a paper describing findings and submit as a proposal to publish/post as a Qiskit tutorial/application-chapter/Qiskit blog

### Mentors details

- Mentor 1
  - Name: Robert Loredo
  - GitHub ID: @robertloredo
  - What they do: IBM Quantum Ambassador worldwide lead

### Number of mentees

4

### Type of mentees

- Mentee 1
  - Required:
    - Computational Web3 knowledge. Able to determine the computational complexity and existing challenges 
    - Proficient in Qiskit
  - Nice to have:
    - Web3 development skills in any of the L1/L2 or other Web3 application development  
    - Quantum information/computation experience
    - Experience in Qiskit open source contributions
- Mentee 2
  - Required:
    - Web3 development skills in any of the L1/L2 or other Web3 applications
    - Proficient in Qiskit
  - Nice to have:
    - Quantum computation/information experience
    - Experience in Qiskit open source contributions

**Comment by jamesquantum** [comment]
@robertloredo I’d love to be involved in this project

**Comment by robertloredo** [comment]
@jamesphysics Welcome aboard! 
Looking forward to getting this project going! 

@HuangJunye FYI.

**Comment by HuangJunye** [comment]
@jamesphysics Can you please provide your checkpoint 2 updates? Instructions are given in [the slack channel](https://qiskit.slack.com/archives/C031KJYKQ84/p1651056055527459).

**Comment by HuangJunye** [comment]
If I understand it correct, this project didn't happen and @robertloredo became a co-mentor for @SiddharthaMorales for #38. Is that right?

**Comment by robertloredo** [comment]
Hi @HuangJunye Yes that is correct. Thanks for checking back. Have a great weekend! 👍
