### ISSUE TITLE
Solving the system of non-linear differential equations using the Carleman linearization

### ISSUE THREAD

**Issue by ljubabu** [qiskit-advocate/qamp-spring-22#30]
### Description

One of the major obstacles in solving multiphysics problems on quantum devices, like the computational fluid dynamics for example, include the non-linearity of corresponding partial diff. equations describing the particular physical process. In order to be able to harvest full potential of the quantum space in solving this complex multiphysics problems, implementation of adequate algorithm is required. One of the approaches for solving non-linear PDF is proposed by J.P. Liu et. al. in paper entitled “Efficient quantum algorithm for dissipative nonlinear differential equations”, where the Carleman linearization in combination with the linear solver is described. Implementation of this algorithm on quantum devices and testing on some practical examples using Qiskit framework is the major goal of this project.     

### Deliverables

Quantum algorithm for solving particular set of non-linear diff. equations using the Qiskit simulator backend.     

### Mentors details

- Mentor 1
  - Name: Budinski Ljubomir
  - GitHub ID: @ljubabu
  - What they do: Use QC to solve CFD problems and part of Qiskit advocate squad

### Number of mentees

1

### Type of mentees

- Mentee 1
  - Required:
    - Interested in developing the quantum algorithms for scientific computations.
  - Nice to have:
    - Knowledge of HHL and VQL algorithms.
    - Fundamental familiarity with partial differential equations.

**Comment by anonymousr007** [comment]
Hi @ljubabu, I am Rishabh, an undergraduate computer engineering student at Delhi Technological University. I am interested in this project. So, can you please share further detail to become a mentee in this project?

**Comment by ljubabu** [comment]
Dear Rishabh,

 

As far as i know (correct me if I’m wrong) the selection process is finished, hence I suggest to first contact the people from Qiskit to see 

if its possible to start the mentorship in this stage. If they agree with this we could than talk little bit about the project. Since this project is

little bit a demanding in sense of underlying mathematics, I have an alternative options (also from the field of scientific computations) that 

we can work on. So, please contact the people from Qiskit first to see if its possible to start the mentorship, and after that we can start working.

 

Best regards,

 

Ljubomir

**Comment by HuangJunye** [comment]
@anonymousr007 Thanks for your interest in the project. In order to participate, you need to become a Qiskit advocate first. You can see more information about how to apply in [the application guide](https://github.com/qiskit-advocate/application-guide).

**Comment by HuangJunye** [comment]
Closing this issue as it was not paired with any mentee. Thank you for suggesting the project idea!
