### ISSUE TITLE
Qiskit-Metal Documentation

### ISSUE THREAD

**Issue by priti-ashvin-shah-ibm** [qiskit-advocate/qamp-spring-22#31]
### Description

We have draft written documentation written in Overleaf LaTex called 
Qiskit Metal:  A quantum device design framework and library.  

We would like to have "professional" type diagrams and figures for the document.  

Contributor would need to understand the flow of the python code and work with various developers to create diagrams that are meaningful. 

### Deliverables

Diagrams added to the latTex document.

### Mentors details

- Mentor 1
  - Name: Priti Shah
  - GitHub ID: @priti-ashvin-shah-ibm 
  - What they do: Qiskit Metal core developer

### Number of mentees

1

### Type of mentees

- Mentor 1
  - Required:
    - python to understand the flow of Qiskit Metal Code
    - Willing to create professional looking diagrams for LaTex
  - Nice to have:
    - Installed and used Qiskit Metal
    - Understand A* algorithm.

**Comment by HuangJunye** [comment]
@priti-ashvin-shah-ibm This project has no mentee working it right? Can I close the issue?

**Comment by HuangJunye** [comment]
Closing the issue now. Please let me know if this is actually being done by a mentee.
