### ISSUE TITLE
Qiskit Metal - During rebuild, only rebuild what needs to be done.

### ISSUE THREAD

**Issue by priti-ashvin-shah-ibm** [qiskit-advocate/qamp-spring-22#34]
### Description

When using Qiskit Metal, after components are added to the design, Rebuild has to happen to populate the Pandas tables.  These tables are QGeometry tables and NetInformation tables.  They are used to render to different tools i.e. Metal GUI, GDS file, Ansys

The Pandas tables have to be accurate.  

The rebuild can waste time when rebuilding components that have not been changed.  The project is to add some logic to determine which components can avoid the need to rebuilt.

### Deliverables

Start a way to identify ways to reduce the number of components that need to be rebuilt.  Mentors can help with that, and the logic needs to be implemented in Metal back-end code. 

### Mentors details

- Mentor 1
  - Name: Priti Shah
  - GitHub ID: @priti-ashvin-shah-ibm
  - What they do: Qiskit Metal core developer

### Number of mentees

1

### Type of mentees

- Mentor 1
  - Required:
    - Python
  - Nice to have:
    - Have installed and used Metal, edited components within a notebook.
    - Created a custom component.

**Comment by HuangJunye** [comment]
@priti-ashvin-shah-ibm This project has no mentee working it right? Can I close the issue?

**Comment by HuangJunye** [comment]
Closing the issue now. Please let me know if this is actually being done by a mentee.
