### ISSUE TITLE
Exploring potential of  Quantum Neural Networks under noise

### ISSUE THREAD

**Issue by cnktysz** [qiskit-advocate/qamp-spring-22#35]
### Description

Quantum neural networks (QNNs) are promising candidates to replace classical feedforward neural networks (Please see work by [Abbas et al.](https://www.nature.com/articles/s43588-021-00084-1)). However, it is still unknown if or when this can happen. Understanding the potential of QNNs requires us to investigate how they perform under many noise effects that we observe on NISQ devices. In this project, we will benchmark several QNNs under different levels of noise (readout assignment error, cnot errors, depolarizing noise, etc.) and see the effect of noise and if widely used error mitigation techniques can allow us to recover the performance.

### Deliverables

Performance benchmarks of QNNs under noise with and without error mitigation.

### Mentors details

- Mentor 
  - Name: Cenk Tüysüz
  - GitHub ID: @cnktysz
  - What they do: Physics PhD student at DESY and Humboldt University of Berlin, research on QML applications for High Energy Physics

### Number of mentees

2

### Type of mentees

Interest in Quantum Machine Learning.
Interest in Error Mitigation and Noisy Quantum Simulations.

**Comment by pdc-quantum** [comment]
Very interested in this project in areas where I already have knowledge. I'm willing to join him as a mentee.

**Comment by HuangJunye** [comment]
@cnktysz would you like to take @pdc-quantum as mentee for this project? Can you please communicate on Slack to discuss? If you have decided to work together, please let me know on Slack. Thank you :)

**Comment by iotaisolutions** [comment]
Interested

**Comment by HuangJunye** [comment]
Closing this issue as the team decided not to proceed beyond the trial period. Hope you have better luck next time and come back for the Fall cohort!
