### ISSUE TITLE
Qiskit integration for artists

### ISSUE THREAD

**Issue by JRussellHuffman** [qiskit-advocate/qamp-spring-22#36]
### Description

Currently, artists who would like to work with Qiskit must figure out how to integrate Qiskit into their creative workflow. This often means translating their work to different programming languages or finding unofficial workarounds, depending on the creative environment. We propose a project to have Qiskit integrated more natively into creative environments (such as Processing). This project would require determining which creative environments are the most used by generative artists and then figuring out how to integrate Qiskit into those environments.

### Deliverables

Having Qiskit integrated into a creative environment (such as [Processing](https://processing.org)) so that generative artists can work natively work with Qiskit directly.

### Mentors details

- Mentor 1
  - Name: Russell Huffman
  - GitHub ID: @JRussellHuffman
  - What they do: Qiskit Design Lead
- Mentor 2
  - Name: Iskandar Sitdikov
  - GitHub ID:@IceKhan13
  - What they do: Qiskit Community Developer Advocate

### Number of mentees

2

### Type of mentees

- Mentee 1
  - Required:
    - Interested in generative art, or creative applications of quantum computing
  - Nice to have:
    - Experience in creative coding, artist's software/environments/libraries

**Comment by HuangJunye** [comment]
This is a very interesting project. I was looking at how to do something similar with game development and Qiskit before joining IBM. So this might be of interest to this project: https://github.com/HuangJunye/Qiskit-for-GameDev (very out of date though). @quantumjim also has a MicroQiskit project that might be useful here: https://github.com/qiskit-community/MicroQiskit

**Comment by JRussellHuffman** [comment]
Actually, @quantumjim already made a version of microqiskit that works directly in Processing. I'm super glad to have it and use it all the time. However, it would be good to have the full version of Qiskit running for educational purposes, as well as using real quantum data as a part of art-making (which is something that I think is important).

**Comment by robertloredo** [comment]
Happy to join to feed my curiosity. :)

**Comment by HuangJunye** [comment]
Closing this issue as it was not paired with any mentee. Thank you for suggesting the project idea!
