### ISSUE TITLE
Vertical circuit drawer

### ISSUE THREAD

**Issue by kevinsung** [qiskit-advocate/qamp-spring-22#40]
### Description

See https://github.com/Qiskit/qiskit-terra/issues/7720. Description copied below.

`QuantumCircuit.draw` should support drawing the circuit with vertical wires instead of horizontal. This is useful when the length of the circuit exceeds the width of the display area. With horizontal wires, this situation results in line wrapping, but with vertical wires no wrapping would be needed because one can scroll, and it's easier to read the circuit contents that way.

### Deliverables

Fix and close https://github.com/Qiskit/qiskit-terra/issues/7720.

### Mentors details

- Mentor 1
  - Name: Kevin J. Sung
  - GitHub ID: kevinsung
  - What they do: Qiskit Researcher

### Number of mentees

1

### Type of mentees

- Mentee 1
  - Required:
    - Knowledge of Python
  - Nice to have:
    - Quantum computing knowledge

**Comment by HuangJunye** [comment]
@kevinsung Thanks for submitting the project idea. Did you close it because of the new discussions on https://github.com/Qiskit/qiskit-terra/issues/7720#issuecomment-1058246863 ?

**Comment by kevinsung** [comment]
@HuangJunye Yes, sorry, I should have mentioned that. I've replaced this project with https://github.com/qiskit-advocate/qamp-spring-22/issues/42.
