### ISSUE TITLE
Change LaTex circuit drawer from qcircuit to qpic

### ISSUE THREAD

**Issue by kevinsung** [qiskit-advocate/qamp-spring-22#42]
### Description

See https://github.com/Qiskit/qiskit-terra/issues/7727.

### Deliverables

Fix https://github.com/Qiskit/qiskit-terra/issues/7727.

### Mentors details

- Mentor 1
  - Name: Kevin Sung
  - GitHub ID: kevinsung
  - What they do: Qiskit Researcher

### Number of mentees

1

### Type of mentees

- Mentee 1
  - Required:
    - Knowledge of Python
  - Nice to have:
    - Knowledge of LaTeX
    - Experience using [qpic](https://github.com/qpic/qpic)

**Comment by HuangJunye** [comment]
Closing this issue as it was not paired with any mentee. Thank you for suggesting the project idea!
